// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHjE3tFnu35cUa3HIbMMH4E8Qgj7omTa4',
    appId: '1:458482601291:web:b03b749e85f4c6f9366cce',
    messagingSenderId: '458482601291',
    projectId: 'fir-auth-895c2',
    authDomain: 'fir-auth-895c2.firebaseapp.com',
    storageBucket: 'fir-auth-895c2.appspot.com',
    measurementId: 'G-ZBVYEMLPGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_WWHDcpw6SCzIqWxWawhhmLr3J3afLc',
    appId: '1:458482601291:android:84943f8b649c1771366cce',
    messagingSenderId: '458482601291',
    projectId: 'fir-auth-895c2',
    storageBucket: 'fir-auth-895c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7rDQ7ZO3X7peLQpC8ni3QQf9-YEI_TZw',
    appId: '1:458482601291:ios:b94388dc77305892366cce',
    messagingSenderId: '458482601291',
    projectId: 'fir-auth-895c2',
    storageBucket: 'fir-auth-895c2.appspot.com',
    iosClientId: '458482601291-6fc4e2t5g5vp76asem2jl79hb0ed3ik9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7rDQ7ZO3X7peLQpC8ni3QQf9-YEI_TZw',
    appId: '1:458482601291:ios:b94388dc77305892366cce',
    messagingSenderId: '458482601291',
    projectId: 'fir-auth-895c2',
    storageBucket: 'fir-auth-895c2.appspot.com',
    iosClientId: '458482601291-6fc4e2t5g5vp76asem2jl79hb0ed3ik9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginSignup',
  );
}
